export enum DataRequestStatus {
  Saved_DataRequest = 1,
  Accepted_DataRequest = 2,
  Saved_AssignDataRequest = 3,
  Accepted_AssignDataRequest = 4,
  Saved_EnterData = 5,
  Accepted_EnterData = 6,
  Rejected_EnterData_IA = -6,
  Rejected_EnterData_DEO = -10,
  Saved_ReviewData = 7,
  Rejected_ReviewData = -8,
  Accepted_ReviewData = 9,
  Saved_ApproveData = 8,
  Rejected_ApproveData = -9,
  Accepted_ApproveData = 11,
}
